Vagrant.configure("2") do |config|
  config.vm.box = "deimos_fr/debian-stretch"
  config.vm.synced_folder "..", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 4
      vb.memory = "4096"
  end

  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant_data
    source tests/k8s-euft/env.bash
    tests/k8s-euft/prerequisites.sh
    docker run -v $(pwd):/go/src/github.com/MySocialApp/k8s-dns-updater -w /go/src/github.com/MySocialApp/k8s-dns-updater \
      golang:1.11-stretch go run tests/k8s-euft/travis-exec.go .travis.yml script
    go run tests/k8s-euft/travis-exec.go .travis.yml install
    go run tests/k8s-euft/travis-exec.go .travis.yml after_success
  SHELL
end
